apiVersion: v1
kind: ConfigMap
metadata:
  name: drift-sentinel-team-a
  namespace: drift-sentinel
  annotations:
    drift-sentinel.k8s.io/rule: "true"
data:
  spec: |
    mode: warn
    priority: 100
    namespaces:
      - "team-a-*"
    selectors:
      - apiGroup: "apps"
        kind: "Deployment"
    exclude:
      - "status"
    mutable:
      - "spec.template.spec.containers[*].image"
      - "spec.template.spec.containers[*].env"
